"""Wardrobe and body specs for every figure the organizer ships.

Colours are sRGB hex. coat/scarf/hat colours become the material factors of the `coat`, `scarf`
and `hat` materials (the engine recolours them per person from crowd.json).
"""

BASE = [
    dict(name="people_man_coat", role="crowd", body="man", H=1.80, skin="#e3b8a0", hair="short", hair_color="#3b2b22",
         coat=dict(style="long", color="#3a3d44", collar="turn", double=True, buttons=3, belt=False),
         scarf=dict(style="wrap", color="#9e2a2b"),
         hat=dict(style="flatcap", color="#6b6158"),
         trousers="#2a2b30", boots=dict(style="boot", color="#3d2a1f"), gloves="#3b2a20"),
    dict(name="people_woman_coat", role="crowd", body="woman", H=1.68, skin="#f0c8b0", hair="long", hair_color="#5a3a26",
         coat=dict(style="long", color="#a8814f", collar="turn", buttons=4, belt=True, flare=1.25, below_knee=0.02),
         scarf=dict(style="wrap", color="#e8dcc6", bulk=1.25),
         hat=dict(style="bobble", color="#7a2436"),
         trousers="#1f1c1e", tights=True, boots=dict(style="tall", color="#1d1a19"), gloves="#5b5b60", lip="#a55a5a"),
    dict(name="people_man_parka", role="crowd", body="man", H=1.76, skin="#c99a7a", hair="short", hair_color="#1d1510",
         beard=True,
         coat=dict(style="mid", color="#27344a", collar="hood", fur="#8a7a66", toggles=True, buttons=4),
         scarf=dict(style="wrap", color="#c8962c"),
         hat=dict(style="beanie", color="#3d5a3e"),
         trousers="#3a4556", boots=dict(style="boot", color="#5a4330"), gloves="#1e1e1e"),
    dict(name="people_woman_older", role="crowd", body="woman", H=1.62, skin="#e8c0a8", hair="bob", hair_color="#b9b4ad",
         glasses=True,
         coat=dict(style="mid", color="#2f4a3a", collar="stand", buttons=4),
         scarf=dict(style="wrap", color="#2e6f73", stripes=(2, 0.6)),
         hat=dict(style="beret", color="#6a2e4f"),
         trousers="#2b2a2c", tights=True, boots=dict(style="boot", color="#4a3325"), gloves="#6b3a2a", bag="#5b3a24",
         lip="#9a5a55"),
    dict(name="people_man_older", role="crowd", body="man", H=1.73, skin="#e6bca6", hair="bald", hair_color="#c9c3bb",
         glasses=True,
         coat=dict(style="long", color="#5b5750", collar="turn", buttons=4),
         scarf=dict(style="wrap", color="#7b2b2b", stripes=(1, 0.55)),
         hat=dict(style="trilby", color="#3b2f27", band="#1c1512"),
         trousers="#34322f", boots=dict(style="shoe", color="#2a1c14"), gloves="#2a211b"),
    dict(name="people_woman_young", role="crowd", body="woman", H=1.70, skin="#d7a58a", hair="long", hair_color="#c9a468",
         coat=dict(style="short", color="#5c1f2e", collar="stand", quilt=0.075, buttons=0, pockets=False, below_hip=0.1),
         scarf=dict(style="long", color="#d9d2c4", stripes=(3, 0.55)),
         hat=dict(style="bobble", color="#8f8a86"),
         trousers="#2a3346", boots=dict(style="snow", color="#d9cdb8", cuff="#efe7da"), gloves="#e5ddd0", lip="#a15a5e"),
    dict(name="people_child_boy", role="crowd", body="child", H=1.18, skin="#f1ccb3", hair="kid", hair_color="#6b4a2e",
         coat=dict(style="short", color="#b23a2e", collar="hood", quilt=0.085, buttons=0, below_hip=0.12, ease=0.02),
         scarf=dict(style="wrap", color="#2f5f9e", bulk=0.9, fringe=False),
         hat=dict(style="earflap", color="#e0a33a"),
         trousers="#2c3e5c", boots=dict(style="snow", color="#2b2b33", cuff="#d8d0c0"), gloves="#2f5f9e", curl=0.7),
    dict(name="people_child_girl", role="crowd", body="child", H=1.28, skin="#e6b596", hair="pigtails", hair_color="#3a2518",
         coat=dict(style="mid", color="#2e5e6e", collar="hood", toggles=True, buttons=3),
         scarf=dict(style="wrap", color="#d9667a", fringe=False),
         hat=dict(style="bobble", color="#f0e6d6"),
         trousers="#6a3a5a", tights=True, boots=dict(style="boot", color="#7a3b2a"), gloves="#d9667a", curl=0.7),
]

BAND = [
    dict(name="people_band_sax", role="band", inst="sax", body="man", H=1.74, skin="#9a6a4c", hair="short",
         hair_color="#161110",
         coat=dict(style="long", color="#1e1f24", collar="turn", buttons=4),
         scarf=dict(style="wrap", color="#6d6e73"),
         hat=dict(style="trilby", color="#26221f", band="#6b1f1f"),
         trousers="#1c1c20", boots=dict(style="shoe", color="#1a1412"), curl=0.75),
    dict(name="people_band_piano", role="band", inst="piano", body="woman", H=1.68, skin="#f2cdb5", hair="long",
         hair_color="#2b1d17",
         coat=dict(style="long", color="#3b3f4a", collar="turn", buttons=4, belt=True),
         scarf=dict(style="wrap", color="#b0403a"),
         hat=dict(style="beret", color="#1f2a44"),
         trousers="#1b1b1f", tights=True, boots=dict(style="tall", color="#1b1716"), curl=0.35, lip="#a0524f"),
    dict(name="people_band_bass", role="band", inst="bass", body="man", H=1.86, skin="#e0b095", hair="short",
         hair_color="#6d4b33", beard=True,
         coat=dict(style="mid", color="#1d2536", collar="turn", double=True, buttons=3),
         scarf=dict(style="wrap", color="#c2a878"),
         hat=dict(style="flatcap", color="#4b4640"),
         trousers="#2d2a26", boots=dict(style="boot", color="#3b2a20"), curl=0.8),
    dict(name="people_band_drums", role="band", inst="drums", body="man", H=1.77, skin="#d9a585", hair="short",
         hair_color="#241a14",
         coat=dict(style="short", color="#4a4d36", collar="hood", buttons=4, below_hip=0.1),
         scarf=dict(style="wrap", color="#7a3b2a"),
         hat=dict(style="beanie", color="#2a2a2e"),
         trousers="#23252b", boots=dict(style="boot", color="#2b211b"), curl=0.85),
]

VENDORS = [
    dict(name="people_vendor_gluehwein", role="vendor", stall="gluehwein", body="woman", H=1.66, skin="#e8a47d", face_detail=True,
         hair="bun", hair_color="#7a4a2a",
         coat=dict(style="short", color="#2b2b30", collar="stand", quilt=0.06, buttons=0, pockets=False,
                   sleeve_mat="body", sleeve_color="#7b1e24", below_hip=0.08),
         apron=dict(color="#6b1a1f"),
         scarf=dict(style="wrap", color="#d6c4a4", bulk=0.9, fringe=False),
         hat=dict(style="bobble", color="#a3242c"),
         trousers="#26262a", boots=dict(style="boot", color="#3a2a20"), curl=0.75, lip="#a55a5a"),
    dict(name="people_vendor_bier", role="vendor", stall="bierstand", body="man", H=1.80, skin="#e09a73", face_detail=True,
         hair="short", hair_color="#5a3b26", beard=True,
         coat=dict(style="short", color="#3d4a36", collar="stand", buttons=5, button_color="#b8a068", pockets=True,
                   sleeve_mat="body", sleeve_color="#d9cfbc", below_hip=0.02),
         apron=dict(color="#3a2a1f", long=True),
         scarf=dict(style="neckerchief", color="#8c2a24"),
         hat=dict(style="trilby", color="#1f3a26", brim_w=0.058, band="#6e5232", crown=0.112, taper=1.6,
                  pinch=0.12, back_up=0.022, curl=0.006, tilt=-0.07, brush="#d8ccb4", clasp="#b8a068"),
         trousers="#3a2b20", boots=dict(style="shoe", color="#2a1c14"), curl=0.75),
    dict(name="people_vendor_wurst", role="vendor", stall="bratwurst", body="man", H=1.76, skin="#d09a76", face_detail=True,
         hair="short", hair_color="#2a201a",
         coat=dict(style="short", color="#3b4452", collar="stand", buttons=0, pockets=False, below_hip=0.06),
         apron=dict(color="#d8d1c2", stripe=True),
         scarf=dict(style="neckerchief", color="#2f4f7f"),
         hat=dict(style="beanie", color="#1e1e22", brim=True),
         trousers="#26282e", boots=dict(style="boot", color="#1e1a18"), curl=0.75, serve_mug=False),
    dict(name="people_vendor_buecher", role="vendor", stall="buecherstand", body="man", H=1.72, skin="#e4a47f", face_detail=True,
         hair="bald", hair_color="#d8d4ce", glasses=True, beard=True,
         coat=dict(style="short", color="#6a5a44", collar="turn", buttons=3, below_hip=0.12),
         scarf=dict(style="long", color="#7d2f35", stripes=(2, 0.7)),
         hat=dict(style="flatcap", color="#5b5145"),
         trousers="#3b3a36", boots=dict(style="shoe", color="#3a2518"), gloves="#4a3a2c", curl=0.75, serve_mug=False),
]

ALL = BASE + BAND + VENDORS
BY_NAME = {s["name"]: s for s in ALL}
